# Generated by Django 4.1.3 on 2022-12-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationConsensus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='location',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='spotted',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='spotter',
            field=models.CharField(max_length=20),
        ),
    ]
