# Generated by Django 4.1.3 on 2022-12-05 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locationConsensus', '0002_alter_interaction_location_alter_interaction_spotted_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EphID',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
