# Generated by Django 4.1.5 on 2023-01-27 21:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('locationConsensus', '0003_delete_ephid_delete_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationID', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='spotted',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='spotter',
        ),
        migrations.AlterField(
            model_name='interaction',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='interaction',
            name='from_user',
            field=models.ForeignKey(default='problem', on_delete=django.db.models.deletion.CASCADE, related_name='spotter', to='locationConsensus.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interaction',
            name='spotted_user',
            field=models.ForeignKey(default='problem2', on_delete=django.db.models.deletion.CASCADE, related_name='spotted', to='locationConsensus.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interaction',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locationConsensus.location'),
        ),
    ]
