# Generated by Django 4.1.5 on 2023-02-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationConsensus', '0004_location_user_remove_interaction_spotted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='interactionID',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='location',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='spotted_user',
        ),
        migrations.AddField(
            model_name='interaction',
            name='spotted_users',
            field=models.CharField(default='lol', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='verificationStatus',
            field=models.CharField(default='lol2', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
