# Generated by Django 4.1.5 on 2023-02-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationConsensus', '0005_remove_interaction_interactionid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='spotted_users',
            field=models.CharField(max_length=20),
        ),
    ]
