# Generated by Django 4.1.5 on 2023-02-06 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locationConsensus', '0006_alter_interaction_spotted_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verificationStatus',
        ),
    ]
