# Generated by Django 4.1.5 on 2023-02-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationConsensus', '0009_remove_user_verificationstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verificationStatus',
            field=models.CharField(default=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True), max_length=20),
        ),
    ]
