# Generated by Django 4.1.5 on 2023-02-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationConsensus', '0010_user_verificationstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verificationStatus',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
