# Generated by Django 4.1.3 on 2023-02-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationConsensus', '0011_alter_user_verificationstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verificationStatus',
        ),
        migrations.AlterField(
            model_name='interaction',
            name='spotted_users',
            field=models.CharField(max_length=50),
        ),
    ]
